---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(glue)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# My function

```{r fun-get_message_fur_color}
#' my_fun Title
#'
#' @param primary_fur_color primary color of interest
#' @importFrom glue glue 
#' @return Used for side effects. output a message in the console
#' @export 
get_message_fur_color <- function(primary_fur_color){
  
  message(glue("We will focus on {primary_fur_color} squirrels"))
  
}

```


```{r examples-get_message_fur_color}

get_message_fur_color(primary_fur_color = "Cinnamon")

```

```{r tests-my_fun}
test_that("get_message_fur_color works", {

  expect_message(
    
    object = get_message_fur_color(primary_fur_color = "Cinnamon"), 
    regexp = "We will focus on Cinnamon squirrels"
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd",
               vignette_name = "squirrels_explorer",
               check = TRUE)
```
