# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

library(dplyr)
test_that("save_as_csv works", {
  my_temp_folder <- tempfile(pattern = "savecsv")
  expect_error(iris %>% save_as_csv(file.path(my_temp_folder, "output.xlsx")),
               regexp = "the extension of the file to create is not the right one")
  
  expect_error(NULL %>% save_as_csv(file.path(my_temp_folder, "output.csv")),
               regexp = "the function is not applied to a data.frame")
  
  expect_error(iris %>% save_as_csv(file.path(my_temp_folder, "does/no/exist.csv")) ,  
               regexp = "the path where the file should be saved does not exist")
  
})

