# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' my_fun Title
#'
#' @param primary_fur_color primary color of interest
#' @importFrom glue glue 
#' @return Used for side effects. output a message in the console
#' @export 
get_message_fur_color <- function(primary_fur_color){
  
  message(glue("We will focus on {primary_fur_color} squirrels"))
  
}

