# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand


#' A function to save csv
#' @param dataset A data frame 
#' @param path_name A file path
#'
#' @return Doesn't eturn anything writes a file to disk
#' @importFrom tools file_ext
#' @importFrom utils  write.csv2
#'
#' @export
#' @examples
#' 
#' library(dplyr)
#' # Create a temporary directory
#' my_temp_folder <- tempfile(pattern = "savecsv")
#' dir.create(my_temp_folder)
#' 
#' data(iris)
#' # ok: the .csv file is saved in the current project
#' iris %>% save_as_csv(file.path(my_temp_folder, "output.csv"))
#' 
#' # ok: the .csv file is saved and the file opens
#' iris %>% save_as_csv(file.path(my_temp_folder, "output.csv")) %>% browseURL() 
save_as_csv <- function(dataset, path_name){
  
  file_extension = file_ext(path_name)
  folder_exists = file.exists(dirname(path_name))
  
  if(file_extension != "csv"){
    
    stop("the extension of the file to create is not the right one")
    
  }
  if(isFALSE(inherits(dataset, "data.frame"))){
    
    
    stop("the function is not applied to a data.frame")
  }
  
  if(isFALSE(folder_exists)){
    
    
    stop("the path where the file should be saved does not exist")
    
  }
  
  write.csv2(dataset, file = path_name)
  
  return(path_name)
  
}


